version: '3.8'

# volumes:
#   vol-emqx-data:
#     name: foo-emqx-data
#   vol-emqx-etc:
#     name: foo-emqx-etc
#   vol-emqx-log:
#     name: foo-emqx-log



services:

  mongo:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    
    ports:
      - 27017:27017
    
    # links:
    #   - emqx

    volumes:
      - /home/jeffersong/mongodata:/data/db

    environment:
      TZ: "America/Guayaquil"
      MONGO_INITDB_ROOT_USERNAME: "jeffersong"
      MONGO_INITDB_ROOT_PASSWORD: "jg0411"
      
  
  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.11
    restart: always
    
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8085:8081
    
    # volumes:
    #   - vol-emqx-data:/opt/emqx/data
    #   - vol-emqx-etc:/opt/emqx/etc
    #   - vol-emqx-log:/opt/emqx/log

    links:
      - mongo
    
    environment:
 
      EMQX_NAME: jeffersong
      EMQX_HOST: 127.0.0.1

      TZ: "America/Guayaquil"

      # password dashboard
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "jg0411"
      #topico
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"
      #?COnectar MOngo
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__SERVER: "mongo:27017"
      EMQX_AUTH__MONGO__POOL: 8
      #*credenciales para ingresar a mongo
      EMQX_AUTH__MONGO__LOGIN: "jeffersong"
      EMQX_AUTH__MONGO__PASSWORD: "jg0411"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin
      #*Base de datos y colección
      EMQX_AUTH__MONGO__DATABASE: "proyect"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "users"
      #*super usiario apagado
      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "users"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"
      #*Cntraseña de usuario
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
      #*
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "users"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"
      #*levantar plugins
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"





    


